# Loading Libraries

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

# Loading Dataset

In [5]:
dataset = pd.read_csv("D:/Pantech Solutions/14_StockPredictionusing_SVMREGRESSION/data.csv")

# Summarize Dataset

In [6]:
dataset.head()

x           y
0  168.181818  160.840244
1  187.878788  159.413657
2  207.575758  157.136809
3  227.272727  159.357847
4  246.969697  157.542862

In [7]:
dataset.columns

Index(['x', 'y'], dtype='object')

In [8]:
dataset.shape

(94, 2)

In [9]:
dataset.size

188

In [10]:
dataset.ndim

2

# Segregate Dataset into 2 Parts - Independent and Dependent Variable

In [11]:
x = dataset.iloc[:,:-1].values

In [12]:
x

array([[ 168.18181818],
       [ 187.87878788],
       [ 207.57575758],
       [ 227.27272727],
       [ 246.96969697],
       [ 266.66666667],
       [ 286.36363636],
       [ 306.06060606],
       [ 325.75757576],
       [ 345.45454545],
       [ 365.15151515],
       [ 384.84848485],
       [ 404.54545455],
       [ 424.24242424],
       [ 443.93939394],
       [ 463.63636364],
       [ 483.33333333],
       [ 503.03030303],
       [ 522.72727273],
       [ 542.42424242],
       [ 562.12121212],
       [ 581.81818182],
       [ 601.51515152],
       [ 621.21212121],
       [ 640.90909091],
       [ 660.60606061],
       [ 680.3030303 ],
       [ 700.        ],
       [ 719.6969697 ],
       [ 739.39393939],
       [ 759.09090909],
       [ 778.78787879],
       [ 798.48484848],
       [ 818.18181818],
       [ 837.87878788],
       [ 857.57575758],
       [ 877.27272727],
       [ 896.96969697],
       [ 916.66666667],
       [ 936.36363636],
       [ 956.06060606],
       [ 975.757

In [13]:
y = dataset.iloc[:,-1].values

In [14]:
y

array([160.84024381, 159.41365734, 157.1368088 , 159.35784736,
       157.54286158, 157.73520716, 159.34756091, 155.23404557,
       155.80774009, 158.3299704 , 157.62585291, 160.47697951,
       158.22940639, 157.41781684, 163.37069148, 160.18481104,
       160.96838974, 158.18080666, 160.13850728, 161.6460876 ,
       159.31922497, 162.56957785, 160.81387414, 161.62873371,
       161.20567768, 166.31061698, 162.77603585, 160.88457814,
       164.84205952, 160.95225209, 164.00863628, 159.86853854,
       161.32847639, 164.57554065, 165.85572104, 164.91849414,
       164.54143071, 164.36748958, 162.20962269, 163.92394795,
       164.63932852, 167.87182021, 166.64178203, 162.62543484,
       166.99665279, 165.77528998, 165.38858024, 168.16274652,
       169.19836268, 169.19589357, 165.85186798, 167.10884798,
       168.58676929, 170.07230238, 167.35983334, 168.14383356,
       166.49945126, 166.51667766, 170.73111225, 172.01551036,
       169.35597976, 171.70403549, 170.61721144, 168.80

# Splitting Dataset into Training and Testing

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0, shuffle=True)

In [17]:
print(f"Count of x_train : {len(x_train)}\t\tCount of y_train : {len(y_train)}")
print(f"Count of x_test  : {len(x_test)}\t\tCount of y_test  : {len(y_test)}")

Count of x_train : 75		Count of y_train : 75
Count of x_test  : 19		Count of y_test  : 19


# Training using Support Vector Regression

In [18]:
from sklearn.svm import SVR

In [19]:
model = SVR(kernel="linear")

In [20]:
model.fit(x_train, y_train)

SVR(kernel='linear')

# Testing for one Sample Value

In [21]:
sample_value = 1763

newSample_value = [[sample_value]]
result = model.predict(newSample_value)
print(result)

[173.76318343]


# Testing for all Test Data

In [22]:
y_prediction = model.predict(x_test)

In [23]:
np.concatenate((y_test.reshape(len(y_test),1), y_prediction.reshape(len(y_prediction),1)),1)

array([[157.1368088 , 157.25872855],
       [164.00863628, 163.11080201],
       [166.49945126, 168.54487023],
       [160.96838974, 160.18476528],
       [157.41781684, 159.55775741],
       [171.70403549, 169.58988335],
       [170.61721144, 169.79888598],
       [172.23891016, 173.35193058],
       [164.57554065, 163.73780988],
       [171.42846734, 173.14292795],
       [175.60730324, 172.72492271],
       [155.23404557, 158.30374167],
       [167.10884798, 167.49985711],
       [172.28509132, 175.44195681],
       [175.53082573, 176.27796731],
       [169.35597976, 169.38088073],
       [155.80774009, 158.51274429],
       [160.81387414, 161.43878103],
       [168.08546823, 172.09791483]])

# Evaluating Model - Mean Squared Error, r2 score

In [24]:
from sklearn.metrics import r2_score

In [25]:
from sklearn.metrics import mean_squared_error

In [26]:
print(f"Mean Squared Error : {np.sqrt(mean_squared_error(y_test, y_prediction))}")
print(f"r2 Score           : {r2_score(y_test, y_prediction)*100}")

Mean Squared Error : 1.9525066893025074
r2 Score           : 90.85290859409976
